namespace Core.Entities;

/// <summary>
/// Represents a shopping cart, containing a unique identifier and a list of items.
/// </summary>
public class ShoppingCart
{
  /// <summary>
  /// Gets or sets the unique identifier for the shopping cart.
  /// This field is required.
  /// </summary>
  public required string Id { get; set; }

  /// <summary>
  /// Gets or sets the list of items in the shopping cart.
  /// Each item is an instance of <see cref="CartItem"/>.
  /// </summary>
  public List<CartItem> Items { get; set; } = [];

  /// <summary>
  /// Id of the selected delivery method.
  /// </summary>
  public int? DeliveryMethodId { get; set; }

  /// <summary>
  /// The client secret used for the payment intent, required by payment providers.
  /// </summary>
  public string? ClientSecret { get; set; }

  /// <summary>
  /// Payment intent ID generated by the payment provider.
  /// </summary>
  public string? PaymentIntentId { get; set; }

  /// <summary>
  /// Gets or sets the coupon applied to the shopping cart, if any.
  /// </summary>
  public AppCoupon? Coupon{ get; set; }
}